# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Authenticator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Authenticator

  pod 'CryptoSwift'
  pod 'SwiftBase32'  

  target 'AuthenticatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AuthenticatorUITests' do
    # Pods for testing
  end

end
